### ISSUE TITLE
Fix: 人数をランダム生成するとWarningが表示される問題

### ISSUE THREAD

**Issue by big-Miyabi** [KeitaKageyama/rdm#20]
# 概要
- `src/pages/random/index.page.tsx`で、80%の確率で人数が5、20%の確率で1~4からランダムな人数が生成されるという処理を行っている
  - 映画館サイトは座席数によって選択する人数が変動するため、それを表現した
- その人数分optionタグを作成し、セレクトボックスで表示している

## 問題点
- サーバーサイドで出力された値とクライアントサイドで出力された値が異なるというエラーが発生する
- `Warning: Text content did not match. Server: "2" Client: "5"`

![スクリーンショット 2021-02-24 0 20 15](https://user-images.githubusercontent.com/47961006/108865366-86fd7080-7636-11eb-8958-9d9e25925d64.png)

下記記事が参考になりそう
- [next.jsで乱数を使う時にハマったメモ](https://zenn.dev/terrierscript/articles/2020-11-03-next-js-random-value)
- パッと読んだ感じgetServerSidePropsを使うのが正解な気がする

現在は80%の確率で人数が5になるようにしているが、ここの記述を`const people = randRange(1, 100);`という風に書き換えると確実にこのエラーが発生するのでデバッグしやすい

上記のように書き換えた場合、http://localhost:3434/random でリロードすると高確率で発生する

**Comment by KeitaKageyama** [comment]
人数はランダムじゃなくて良い気がする、、、(席と値段と作品がランダム)

**Comment by big-Miyabi** [comment]
@KeitaKageyama

でも結局ランダム必要じゃんー？
このランダム部分ってどうやって実装したの?
